export const fileConversionPaths = {
  paths: [
    { from: "pdf", to: "html" },
    { from: "jpg", to: "png" },
    { from: "png", to: "jpeg" },
    { from: "png", to: "tiff" },
    { from: "png", to: "jpg" },
    { from: "jpg", to: "tiff" },
    { from: "jpeg", to: "png" },
    { from: "tiff", to: "jpg" },
    { from: "jpeg", to: "tiff" },
    { from: "tiff", to: "jpeg" },
    { from: "png", to: "gif" },
    { from: "gif", to: "png" },
    { from: "jpeg", to: "gif" },
    { from: "gif", to: "jpeg" },
    { from: "jpg", to: "gif" },
    { from: "gif", to: "jpg" },
    { from: "png", to: "webp" },
    { from: "webp", to: "png" },
    { from: "jpeg", to: "webp" },
    { from: "webp", to: "jpeg" },
    { from: "jpg", to: "webp" },
    { from: "webp", to: "jpg" },
    { from: "png", to: "tif" },
    { from: "tif", to: "png" },
    { from: "jpeg", to: "tif" },
    { from: "tif", to: "jpeg" },
    { from: "jpg", to: "tif" },
    { from: "tif", to: "jpg" },
  ],
};
